# Generated by Django 2.2.5 on 2019-09-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_fortune100'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='processing', max_length=200),
        ),
    ]
